### ISSUE TITLE
Assistance Setting Up

### ISSUE THREAD

**Issue by willjrowe** [bigboxer23/meural-control#131]
Hi first of all thank you so much for providing this awesome repo! I just purchased my first Meural product and am super excited to play around with stuff like this. I am a bit of a novice when it comes to hosts/networking/servers/ports/etc. lol so I was hoping you could help me configure my `application.properties` to run your service. I am hoping to run all of this on my personal laptop but would be willing to purchase a raspberry pi or something similar if necessary.

Currently this is what my `application.properties` looks like:

```
server.port:8081
logbackserver=192.168.0.7:5671
meural-api=https://api.meural.com/v0/
meural-account=<user>
meural-password=<pw>
meural-playlist=test
meural-orientation=vertical
host=192.168.0.6
```

I pretty much just put random IPs / ports in hopes it would work but I'm fairly certain there are some more settings / paths I need to configure. (particularly in the `install.sh` script, etc.)

Please let me know if there's any more info I can provide. Also I would be more than happy to contribute to the documentation adding any experiences / difficulties I had in order to help others in the future.

Thanks!

**Comment by bigboxer23** [comment]
Hi, happy to provide some help!  Some of these properties are probably going to depend on what you're trying to accomplish with your meural (google photos integration, leveraging Dall-e for image generation, etc), but let's start with some basics

1. There are probably a few other items you want to add to your `application.properties`:

```gPhotos-albumTitle=
scheduler-time=0 0 0/6 * * ?
openai-key=
openai-prompt=
openai-save-album=
jwst-save-album=
transform-preview-commmand=
transform-commmand=```

Depending on which sources you plan on using, you may need real values for these (or not). 

2. The IP addresses for host and logbackserver defined are probably not important for installing and running this locally, nor is the `install.sh` file which is only needed to install to a remote machine.

3. I'd also recommend updating the `logback.xml` file so logs are written locally by making this change: 

`<root level="INFO">
	<appender-ref ref="STDOUT" />
	<!--<appender-ref ref="stash" />-->
</root>
`

Let me know if this makes sense or if you're stuck on another part of this.
